### ISSUE TITLE
Fastlink connection issues

### ISSUE THREAD

**Issue by TehPigYT** [PerformanC/FastLink#2]
Fastlink does not receive the connected status from the nodelink server if the nodelink server is already online and awaiting for connections.

If the fastlink connection is open before the nodelink server starts, it works normally.

**Comment by ThePedroo** [comment]
Could you be more specific and send us logs?

**Comment by TehPigYT** [comment]
I explained the demonstration.

**Comment by ThePedroo** [comment]
Issues related with WebSocket connection could have been fixed with https://github.com/PerformanC/FastLink/commit/84987bf3c1a3410f2878d8e4f49b5a9c6bde8305, could you try it out and let me know the results?
