### ISSUE TITLE
[BUG]: Spotify Playlist does not work

### ISSUE THREAD

**Issue by ZuherLaith** [PerformanC/FastLink#9]
### FastLink version

2.4.2

### Description

As basic and mentioned in title, when requesting a spotify playlist it doesn't work, but a single spotify track does work.

### Steps to reproduce

1. Start your FL player on NL.
2. Request any Spotify playlist, [example](https://open.spotify.com/playlist/20E9fY4gRvUUwklD1ItFMa?si=c67db372882d4d6d)
3. See the result.

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

**Comment by ThePedroo** [comment]
I couldn't reproduce this on v2.1.0 https://github.com/PerformanC/NodeLink/commit/cdffbbffb8ef359bef21c639c2a2b9a4e82477b9
